import { getCase } from '../data/cases';
const esc = (s: string) => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
/** Original interface reconstructions for explicitly labeled concept studies. */
export function conceptArt(slug: string, state: 'before' | 'after' = 'after'): string {
  const d = getCase(slug); const after = state === 'after'; const rows = after ? d.after : d.before;
  const field = slug === 'fieldnote'; const threshold = slug === 'threshold';
  const heading = field ? 'Make the next decision clearer.' : threshold ? 'What would you like to do first?' : 'A clear route for every request.';
  const subtitle = field ? 'Expertise connected to examples.' : threshold ? 'Explore a guided task before setting up.' : 'Your request, its context, and the next step.';
  const text = (x:number,y:number,s:string,size=22,fill='#273229',weight='400') => `<text x="${x}" y="${y}" font-family="Arial,sans-serif" font-size="${size}" fill="${fill}" font-weight="${weight}">${esc(s)}</text>`;
  const rowHeight = after ? 92 : 62;
  const items = rows.map((label,i) => `<rect x="${after?300:82}" y="${270+i*rowHeight}" width="${after?585:860}" height="${after?76:49}" rx="10" fill="${after&&i===0?d.color:'#ffffff'}" stroke="#ccd2c9"/>${text(after?324:103,after?314+i*rowHeight:302+i*rowHeight,`${String(i+1).padStart(2,'0')}  ${label}`,after?23:20,after&&i===0?'#ffffff':'#344039',after&&i===0?'600':'400')}${after?text(835,314+i*rowHeight,'→',26,i===0?'#ffffff':d.color):''}`).join('');
  const side = after ? `<rect x="68" y="264" width="195" height="390" rx="12" fill="#e7ebe2"/>${text(88,303,field?'FIELD NOTES':threshold?'YOUR GOAL':'REQUEST',15,d.color,'700')}${text(88,347,field?'01 / Strategy':threshold?'First useful task':'Website handoff',18)}${text(88,383,field?'02 / Identity':threshold?'Example workspace':'Priority: normal',17)}${text(88,421,field?'03 / Systems':threshold?'No setup required':'Owner: unassigned',17)}<path d="M90 469 H240" stroke="#aeb9aa"/>${text(88,507,field?'Read an example':threshold?'Your pace.':'Context stays here.',16)}${text(88,542,field?'before deciding.':threshold?'Your decision.':'Review before send.',16)}` : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="960" viewBox="0 0 1024 768"><rect width="1024" height="768" fill="${after?'#e5eade':'#ebe6dd'}"/><rect x="38" y="35" width="948" height="694" rx="18" fill="#f8f9f4" stroke="#bcc7b6"/><path d="M38 96 H986" stroke="#d5dccd"/>${text(68,74,d.name.toUpperCase(),22,d.color,'700')}${text(610,74,after?'OVERVIEW   /   WORK   /   NOTES':'DASHBOARD   /   TOOLS   /   MORE',14)}${text(68,152,after?'REDESIGNED CONCEPT':'CONSTRUCTED STARTING STATE',13,d.color,'700')}${text(68,202,after?heading:'Everything competes for attention.',30,'#1a281e','600')}${text(68,236,after?subtitle:'One flat list. Every action looks equally important.',18,'#596351')}${side}${items}${text(68,702,'Quiet Compass · Concept interface, not a client product',13,'#596351')}</svg>`;
}
