// @ts-nocheck
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const root=document.documentElement;
const base=document.body.dataset.base||'/';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const prefs={get(k,f=null){try{return localStorage.getItem('qc:'+k)??f}catch{return f}},set(k,v){try{localStorage.setItem('qc:'+k,v)}catch{}}};

const savedTheme=prefs.get('theme');if(savedTheme)root.dataset.theme=savedTheme;
$$('[data-theme-toggle]').forEach(b=>b.addEventListener('click',()=>{const n=root.dataset.theme==='dark'?'light':'dark';root.dataset.theme=n;prefs.set('theme',n);track('theme_change',{theme:n})}));

const reveals=$$('[data-reveal]');
if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12});reveals.forEach(x=>io.observe(x))}else reveals.forEach(x=>x.classList.add('is-visible'));

const sectionObserver='IntersectionObserver'in window?new IntersectionObserver(es=>{const visible=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;const el=visible.target;root.dataset.element=el.dataset.element||'earth';const bearing=el.dataset.bearing||'0';$$('.compass').forEach(c=>c.style.setProperty('--bearing',bearing+'deg'));$$('[data-route-link]').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+el.id));const route=el.querySelector('.route-svg');if(route)route.classList.add('is-active')},{threshold:[.2,.45,.7]}):null;sectionObserver&&$$('section[id], [data-route-section]').forEach(s=>sectionObserver.observe(s));

if(!reduced&&matchMedia('(pointer:fine)').matches){
  $$('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)*.08,y=(e.clientY-r.top-r.height/2)*.08;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
  $$('[data-tilt]').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();const rx=((e.clientY-r.top)/r.height-.5)*-3,ry=((e.clientX-r.left)/r.width-.5)*4;el.style.transform=`perspective(900px) rotateX(${rx}deg) rotateY(${ry}deg)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
  const preview=$('#cursor-preview');$$('[data-preview]').forEach(el=>{el.addEventListener('pointerenter',()=>{preview.textContent=el.dataset.preview;preview.classList.add('is-visible')});el.addEventListener('pointermove',e=>{preview.style.transform=`translate(${e.clientX+18}px,${e.clientY+18}px)`});el.addEventListener('pointerleave',()=>preview.classList.remove('is-visible'))});
}

const palette=$('#command-palette'),open=$$('[data-command-open]'),close=$('[data-command-close]'),input=$('#command-input'),results=$('#command-results');let lastFocus;
const commands=[['Home',''],['Work','work/'],['About','about/'],['Journal','journal/'],['Contact','contact/'],['Atlas','projects/atlas/'],['Fieldnote','projects/fieldnote/'],['Threshold','projects/threshold/']];
function renderCommands(q=''){if(!results)return;const term=q.trim().toLowerCase();const rows=commands.filter(([n])=>!term||n.toLowerCase().includes(term));results.innerHTML=rows.map(([n,p])=>`<a href="${base}${p}">${n}</a>`).join('')||'<p class="status">No route found.</p>';if(term)loadPagefind(term)}
async function loadPagefind(q){try{results.innerHTML='<div class="skeleton" style="height:62px;border-radius:12px"></div>'+results.innerHTML;const pf=await import(/* @vite-ignore */ base+'pagefind/pagefind.js');const r=await pf.search(q);const data=await Promise.all(r.results.slice(0,6).map(x=>x.data()));results.innerHTML=data.map(d=>`<a href="${d.url}"><strong>${d.meta?.title||d.url}</strong><br><span class="route">${d.excerpt||''}</span></a>`).join('')||'<p class="status">No indexed route found.</p>';track('search_used',{query_length:q.length,result_count:data.length})}catch{}}
open.forEach(b=>b.addEventListener('click',()=>{lastFocus=document.activeElement;palette?.showModal();renderCommands();setTimeout(()=>input?.focus(),0)}));close?.addEventListener('click',()=>palette?.close());palette?.addEventListener('close',()=>lastFocus?.focus());input?.addEventListener('input',e=>renderCommands(e.target.value));document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open[0]?.click()}});

const filterButtons=$$('[data-filter]'),projects=$$('[data-project]'),filterStatus=$('#filter-status');
function applyFilters(){const active={};filterButtons.filter(b=>b.getAttribute('aria-pressed')==='true').forEach(b=>(active[b.dataset.group]=b.dataset.filter));let count=0;projects.forEach(p=>{const show=Object.entries(active).every(([g,v])=>v==='all'||(p.dataset[g]||'').split(',').includes(v));p.hidden=!show;if(show)count++});if(filterStatus)filterStatus.textContent=`${count} route${count===1?'':'s'} found`;const u=new URL(location.href);Object.entries(active).forEach(([g,v])=>v==='all'?u.searchParams.delete(g):u.searchParams.set(g,v));history.replaceState(null,'',u);prefs.set('filters',u.searchParams.toString());track('filter_changed',{count})}
if(filterButtons.length){const u=new URL(location.href);const saved=new URLSearchParams(prefs.get('filters',''));filterButtons.forEach(b=>{const q=u.searchParams.get(b.dataset.group)||saved.get(b.dataset.group);if(q)b.setAttribute('aria-pressed',String(b.dataset.filter===q));b.addEventListener('click',()=>{filterButtons.filter(x=>x.dataset.group===b.dataset.group).forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');applyFilters()})});applyFilters()}

const intentButtons=$$('[data-intent]');
function applyIntent(val){if(!val)return;intentButtons.forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.intent===val)));const list=$$('[data-project]');list.sort((a,b)=>Number((b.dataset.service||'').includes(val))-Number((a.dataset.service||'').includes(val))).forEach(el=>el.parentElement?.appendChild(el))}
applyIntent(prefs.get('intent'));intentButtons.forEach(b=>b.addEventListener('click',()=>{const val=b.dataset.intent;prefs.set('intent',val);applyIntent(val);track('intent_selected',{intent:val})}));

$$('[data-before-after] input').forEach(r=>r.addEventListener('input',e=>{const box=e.target.closest('[data-before-after]');box.querySelector('.after').style.clipPath=`inset(0 ${100-e.target.value}% 0 0)`}));
$$('[data-diagram-step]').forEach(b=>b.addEventListener('click',()=>{const status=b.closest('[data-diagram]')?.querySelector('[data-diagram-status]');const copy={Research:'Research isolates the real constraint and removes false urgency.',Decision:'The design compresses the problem into the few choices that matter now.',Outcome:'The route ends with evidence and a clear next action.'};if(status)status.textContent=copy[b.dataset.diagramStep]||''}));

const form=$('#contact-form'),formStatus=$('#form-status');if(form)form.dataset.started=String(Date.now());
form?.addEventListener('submit',async e=>{e.preventDefault();const honeypot=form.querySelector('[name="website"]');if(honeypot?.value)return;const endpoint=form.dataset.endpoint;if(!endpoint){formStatus.textContent='The secure submission endpoint is not configured on this deployment yet.';return}const started=Number(form.dataset.started||Date.now());if(Date.now()-started<1200){formStatus.textContent='Please take a moment to review your note.';return}formStatus.textContent='Sending…';const data=Object.fromEntries(new FormData(form));try{const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error();formStatus.textContent='Sent. Your route is on its way.';form.reset();form.dataset.started=String(Date.now());track('contact_succeeded',{})}catch{formStatus.textContent='Could not send yet. Your message is still here—please try again.'}});

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register(base+'sw.js').catch(()=>{}));
$$('a[data-prefetch]').forEach(a=>{let done=false;const go=()=>{if(done)return;done=true;const l=document.createElement('link');l.rel='prefetch';l.href=a.href;document.head.appendChild(l)};a.addEventListener('pointerenter',go,{once:true});a.addEventListener('focus',go,{once:true})});

const analyticsEndpoint=import.meta.env.PUBLIC_ANALYTICS_ENDPOINT||'';
function track(name,detail={}){if(!analyticsEndpoint)return;const body=JSON.stringify({name,path:location.pathname,detail,ts:Date.now()});if(navigator.sendBeacon)navigator.sendBeacon(analyticsEndpoint,new Blob([body],{type:'application/json'}));else fetch(analyticsEndpoint,{method:'POST',headers:{'content-type':'application/json'},body,keepalive:true}).catch(()=>{})}
if(analyticsEndpoint){import('web-vitals').then(({onCLS,onINP,onLCP})=>{[onCLS,onINP,onLCP].forEach(fn=>fn(metric=>track('web_vital',{name:metric.name,value:metric.value,rating:metric.rating})))})}

if(import.meta.env.PUBLIC_FEATURE_WEBGL==='true'&&!reduced){const canvas=$('[data-webgl]');if(canvas&&'IntersectionObserver'in window){const io=new IntersectionObserver(async es=>{if(!es[0].isIntersecting)return;io.disconnect();const THREE=await import('three');const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.z=3;const geo=new THREE.TorusGeometry(.7,.02,16,120),mat=new THREE.MeshBasicMaterial({color:0x708e96});const ring=new THREE.Mesh(geo,mat);scene.add(ring);const resize=()=>{const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()};resize();new ResizeObserver(resize).observe(canvas);const tick=()=>{ring.rotation.z+=.002;ring.rotation.x=.5;renderer.render(scene,camera);requestAnimationFrame(tick)};tick()},{rootMargin:'200px'});io.observe(canvas)}}
