import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseBody,validateInquiry,safeAnalytics} from '../lambda/input.ts';
const valid={name:'Test reviewer',email:'reviewer@example.test',message:'This is a unit-test note, not a real inquiry.'};
test('JSON and native form payloads validate without truncating',()=>{assert.deepEqual(validateInquiry(parseBody(JSON.stringify(valid),false,'application/json')).errors,{});assert.deepEqual(validateInquiry(parseBody(new URLSearchParams(valid).toString(),false,'application/x-www-form-urlencoded')).errors,{});});
test('base64 and malformed/oversized data',()=>{assert.equal(parseBody(Buffer.from(JSON.stringify(valid)).toString('base64'),true,'application/json').name,valid.name);for(const body of ['[]','null','not json','x'.repeat(110000)])assert.throws(()=>parseBody(body,false,'application/json'));});
test('required fields, length and header safety',()=>{assert.equal(Object.keys(validateInquiry({}).errors).length,3);assert.ok(validateInquiry({...valid,email:'invalid'}).errors.email);assert.ok(validateInquiry({...valid,message:'x'.repeat(4001)}).errors.message);assert.ok(validateInquiry({...valid,project:'Header\r\nInjected'}).errors.project);});
test('analytics strips user content and unrecognized paths',()=>{const safe=safeAnalytics({name:'search_used',path:'/Vetomin/contact/?email=private@example.test',detail:{query:'sensitive',email:'private@example.test',message:'secret',result_count:3}});assert.equal(safe.path,'/Vetomin/contact/');assert.deepEqual(safe.detail,{result_count:3});assert.equal(safeAnalytics({name:'contact_failed',path:'/people/private@example.test/'}).path,'/other/');});
test('metric validation is finite and categorical',()=>{assert.throws(()=>safeAnalytics({name:'web_vital',detail:{metric:'LCP',device:'mobile',value:Infinity}}));const result=safeAnalytics({name:'web_vital',path:'/Vetomin/',detail:{metric:'LCP',device:'mobile',value:1200}});assert.equal(result.detail.value,1200);assert.throws(()=>safeAnalytics({name:'arbitrary_sensitive_event'}));});
